from collections import Counter    

vigi_out = 'KMNLKSTEIWXAPQEXVPRHOJOIRCUSQIBRLRWSUSPMOTEWYMZESHOJHDRCUSXREJHIMVWCWGREPVDSKEIWCWTHIXFPWOYEXXDERFJFVDTKIXMXWXLFOIRSFOIROFXDLOFFRHCUSQIBRTLQQJZWWOXCIYNWMIVOAEIRULYRIXMXIMXLCMZSSWIWLWTWTSWWDYXWSQIXOPVZYFFRWEFEIVJAPLXCANLNOSYWXBWYKIXVPVODJAIVVANLIBTPXFDARYRQSFWWOJFQZYJEIMVWOEVKMDDYJAPLIXQLFIBOPVLKLTVKOFOIMXJPGLDWTRIXEPRWMZPRDELLHIVFOIVNAPIRDKNLISVFRKDJTJJDWTRIPJPYHORFKIXAPWWOFOMIUWTRIEFLRKOFPLQOFQSPQWYLEDGOIVOAYIRNWCWGREPVDFWCQISVPXAODNLIBCPMROVLVEEKCIWEDEMIBWYHIPJPYHOFLGLCANLDSWSXCKMNLKSTEIWXAPQEXVPRHOJOIRCUSQIBRLRWSUSPMOTEWYMZESHOJHDRCUSXREJHIMVWCWGREPVDSKEIWCWTHIXFPWOYEXXDERFJFVDTKIXMXWXLFOIRSFOIROFXDLOFFRHCUSQIBRTLQQJZWWOXCIYNWMIVOAEIRULYRIXMXIMXLCMZSSWIWLWTWTSWWDYXWSQIXOPVZYFFRWEFEIVJAPLXCANLNOSYWXBWYKIXVPVODJAIVVANLIBTPXFDARYRQSFWWOJFQZYJEIMVWOEVKMDDYJAPLIXQLFIBOPVLKLTVKOFOIMXJPGLDWTRIXEPRWMZPRDELLHIVF'
schluessellaenge=5
i=0

def findkey(text_enc, keylength):
    for i in range(keylength):
        txt_sub = vigi_out[i::keylength]
        c = Counter(txt_sub)
        letter_most_common = c.most_common()[0][0]
        shift = (26+ord(letter_most_common)-ord("E"))%26
        print(chr(65+shift))
