import re


def preprocess_text(text):
    # Capitalize the entire text
    text = text.upper()

    # Replace capitalized umlauts with the corresponding letter combinations
    replacements = {
        "Ä": "AE",
        "Ö": "OE",
        "Ü": "UE",
    }

    for original, replacement in replacements.items():
        text = text.replace(original, replacement)

    # Remove all characters other than A-Z
    text = re.sub(r"[^A-Z]", "", text)

    return text


def count_letters(eingabe, normalize=True, as_dict=False):
    # Helper function to count how many times each letter of the alphabet appears in a text
    letters_count = [0] * 26  # Initialize a list with 26 zeros for A-Z

    # Count occurrences of each letter manually
    for char in eingabe:
        if "A" <= char <= "Z":  # Ensure the character is an uppercase letter
            index = ord(char) - ord("A")
            letters_count[index] += 1

    # Normalize counts by the length of the input
    if normalize:
        total_length = len(eingabe)
        if total_length > 0:
            letters_count = [occ / total_length for occ in letters_count]

    # Return as a dictionary if as_dict is True
    if as_dict:
        return {chr(i + ord("A")): letters_count[i] for i in range(26)}

    return letters_count


# txt = "AGUNTBMJSQPNAOVZILVFPMKJPOPBIHVBLUJLZBLVILVKLAULQEOJKUINSMKUCPKNTLCGTQEOUGPVGZTGIMPZQPKQGZMTNMILVFKQGMCGYAQSKJLAGLTGUOGZKJHNHLVKZBYPMFPMOLQPLQEOJKUAQNTWLKMSQEOUGPVDLAVLZUVOCUHKULGTOGMCGOTGCWPYCJPOGTLCZMKUDGYAWUSGULCZAOLQPLSWUAVKITBVVLZNLQFLBKJPMVMPUBGQMVGBPPKJAHGPKJUMPUQEOBGPVGUAVYQEOCPKJKUVKLMKUOTVMUZMTLZOHTGYOGDMULVCSAKULKLAGUIWNMPITKJSGUEGUVFHANPMDLBCSCOTQEOLCTXHACPKLKLPQOMUVVPLIPKMTVJGYNNHMEOMFLZWULWYKJKZKUONPKJLVHPVUAMTUQUTMKUMUDINKMUYCJACPKVWYMKUHGSVGZBTHPNLVUPKJPVFHAKUVGYMJLQNPOVBUUAMJSMPPKJKIPUQOOWJLVIYIULIOMINSMPKMPIIEOMNPMILCPKVCLPGYIPKMTLZFLBCBAGULOHVPPOHHTVPOGNZCLAEOMPTQTTMTREWLZFPOYLZFLVYLVPPKJKIUDQOTMNULGYSNLQPLVYLTVGEKZKJLVJHTOLVFPMWUHCLPNPOGUCPLZIYCGULNPKJLVILAVHTVLVFLZYBMTTKJLVFLZOBMERKJLVPHMJLZCUUGPVGTPGYHGUNWLPNLCPKNWLPNLLKLOGNMPDITALGZINSUCLKJAQILVFLZWUAPHKJZMKUMOIQNKMUJPWMLCZEGOMPKMUHTNPMDLVFLVFLZWUAKUMYPOGYEQUVGZKJDMDLVFAZCLOVBVFLZJHMNAUGPVHYMWULYLVPZLCUVWTUGPVGHCILVFHMOTMTACPKLKLEGSBWTUKJPJLZWULFLZJPUOLTIHVBPVOLQPLZULMNLZWOVYPMFPMILAVHTVLQPLZILTKLJVLVFHVPZMJUMKJPOPKJVNVBVFKMPRMCJPMVMPUBGZBFBLCZEKLLGYIWZLTBMERMPRWGUVVLAVKCFLURHXKLZGKIULQPOIWJPGUECZAQCWNSAQDITTQPKQTSMDALCZAGZEWLZFLLGYARPMILTFLQPLZULMNLEKLLGPVGZMGSMKZBFLZUWQGNMNKMUBVGULNPKJLVIVBVLAOLQPMZGBVFHJGYQEOOGOMFHZWLJGYHWNZWULGPKJLZNPMILCPAMTKMTNMYHTVKMTOMTYTKJPMLQVKQGZMTLZUJPGPVWUOGUMKUMYBVFLZDHZGOMKAMTRMKAPCAUGPVGNIPGMULMNLMKUOGUWOTMPNTGPKJKMPZCGZAGUNTBMJSQPNAOVZILVFPMKJPOPBIHVBLUJLZBLVILVKLAULQEOJKUINSMKUCPKNTLCGTQEOUGPVGZTGIMPZQPKQGZMTNMILVFKQGMCGYAQSKJLAGLTGUOGZKJHNHLVKZBYPMFPMOLQPLQEOJKUAQNTWLKMSQEOUGPVDLAVLZUVOCUHKULGTOGMCGOTGCWPYCJPOGTLCZMKUDGYAWUSGULCZAOLQPLSWUAVKITBVVLZNLQFLBKJPMVMPUBGQMVGBPPKJAHGPKJUMPUQEOBGPVGUAVYQEOCPKJKUVKLMKUOTVMUZMTLZOHTGYOGDMULVCSAKULKLAGUIWNMPITKJSGUEGUVFHANPMDLBCSCOTQEOLCTXHACPKLKLPQOMUVVPLIPKMTVJGYNNHMEOMFLZWULWYKJKZKUONPKJLVHPVUAMTUQUTMKUMUDINKMUYCJACPKVWYMKUHGSVGZBTHPNLVUPKJPVFHAKUVGYMJLQNPOVBUUAMJSMPPKJKIPUQOOWJLVIYIULIOMINSMPKMPIIEOMNPMILCPKVCLPGYIPKMTLZFLBCBAGULOHVPPOHHTVPOGNZCLAEOMPTQTTMTREWLZFPOYLZFLVYLVPPKJKIUDQOTMNULGYSNLQPLVYLTVGEKZKJLVJHTOLVFPMWUHCLPNPOGUCPLZIYCGULNPKJLVILAVHTVLVFLZYBMTTKJLVFLZOBMERKJLV"
# print(count_letters(txt, normalize=False, as_dict=True))
